// Date: 17/08/2013 12:19:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package zombiecraft.Core.towers.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTurretCanon extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer BaseArm;
    ModelRenderer HeadArm;
    ModelRenderer HeadBase;
    ModelRenderer Canon;
    ModelRenderer visor;
    ModelRenderer Wings;
  
  public ModelTurretCanon()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(-7F, 0F, -8F, 14, 2, 16);
      Base.setRotationPoint(0F, 23F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      BaseArm = new ModelRenderer(this, 0, 0);
      BaseArm.addBox(-3F, -11F, -1F, 6, 12, 2);
      BaseArm.setRotationPoint(0F, 23F, 0F);
      BaseArm.setTextureSize(64, 32);
      BaseArm.mirror = true;
      setRotation(BaseArm, -0.8552113F, 0F, 0F);
      HeadArm = new ModelRenderer(this, 0, 6);
      HeadArm.addBox(-3F, -8F, -1F, 6, 10, 2);
      HeadArm.setRotationPoint(0F, 16F, 7F);
      HeadArm.setTextureSize(64, 32);
      HeadArm.mirror = true;
      setRotation(HeadArm, 1.291544F, 0F, 0F);
      HeadBase = new ModelRenderer(this, 8, 3);
      HeadBase.addBox(-5F, -1F, -3F, 10, 3, 12);
      HeadBase.setRotationPoint(0F, 13F, 0F);
      HeadBase.setTextureSize(64, 32);
      HeadBase.mirror = true;
      setRotation(HeadBase, 0F, 0F, 0F);
      Canon = new ModelRenderer(this, 0, 25);
      Canon.addBox(-4F, 0F, -8F, 8, 1, 6);
      Canon.setRotationPoint(0F, 13F, 0F);
      Canon.setTextureSize(64, 32);
      Canon.mirror = true;
      setRotation(Canon, 0F, 0F, 0F);
      visor = new ModelRenderer(this, 28, 21);
      visor.addBox(-1F, -2F, -3F, 2, 2, 9);
      visor.setRotationPoint(0F, 13F, 0F);
      visor.setTextureSize(64, 32);
      visor.mirror = true;
      setRotation(visor, 0F, 0F, 0F);
      Wings = new ModelRenderer(this, 0, 0);
      Wings.addBox(-8F, 0F, 0F, 16, 1, 15);
      Wings.setRotationPoint(0F, 13F, 0F);
      Wings.setTextureSize(64, 32);
      Wings.mirror = true;
      setRotation(Wings, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    BaseArm.render(f5);
    HeadArm.render(f5);
    HeadBase.render(f5);
    Canon.render(f5);
    visor.render(f5);
    Wings.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
